export type Sport = {
  name: string;
  slug: string;
  blurb: string;
  tagline: string;
  color: string;
  href: string;
  productCount: number;
};

export const SPORTS: Sport[] = [
  {
    name: "Soccer",
    slug: "soccer",
    blurb: "Matchweight knits, engineered for 90 minutes of intensity.",
    tagline: "Play the beautiful game in fabric that moves with you.",
    color: "#3dd9ff",
    href: "/sports/soccer",
    productCount: 8,
  },
  {
    name: "Cricket",
    slug: "cricket",
    blurb: "Breathable, sweat-wicking kits built for long spells in the sun.",
    tagline: "Command the crease in cooling, quick-dry performance mesh.",
    color: "#c6ff3d",
    href: "/sports/cricket",
    productCount: 5,
  },
  {
    name: "Basketball",
    slug: "basketball",
    blurb: "4-way stretch jerseys that survive the full-court sprint.",
    tagline: "Explosive cuts. Unforgiving durability. Zero restrictions.",
    color: "#ff9b3d",
    href: "/sports/basketball",
    productCount: 5,
  },
  {
    name: "Baseball",
    slug: "baseball",
    blurb: "Pinstripe-ready button-downs and moisture-control pullovers.",
    tagline: "Nine innings of comfort, from the first pitch to the last out.",
    color: "#ff4d2e",
    href: "/sports/baseball",
    productCount: 4,
  },
  {
    name: "Ice Hockey",
    slug: "ice-hockey",
    blurb: "Abrasion-tested layers built for glass-to-glass battles.",
    tagline: "Hit the boards in kit that takes the impact back.",
    color: "#7a8cff",
    href: "/sports/ice-hockey",
    productCount: 5,
  },
  {
    name: "Track Suit",
    slug: "track-suit",
    blurb: "Technical warm-up pieces built for pre-game and recovery.",
    tagline: "Arrive sharp. Recover smart.",
    color: "#ff9b3d",
    href: "/products/track-suits",
    productCount: 3,
  },
  {
    name: "Hoodies",
    slug: "hoodies",
    blurb: "Brushed-back fleece with team-ready customization.",
    tagline: "Street-ready, field-durable.",
    color: "#c6ff3d",
    href: "/products/hoodies",
    productCount: 5,
  },
  {
    name: "Duffel Bags",
    slug: "duffel",
    blurb: "Heavy-duty gear bags built for match day and travel.",
    tagline: "Carry your game.",
    color: "#3dd9ff",
    href: "/products/duffel-bags",
    productCount: 5,
  },
  {
    name: "Karate",
    slug: "karate",
    blurb: "Traditional and modern gi built for kata and kumite.",
    tagline: "Discipline in every stitch.",
    color: "#ff4d2e",
    href: "/sports/karate",
    productCount: 5,
  },
];

export type Product = {
  id: string;
  name: string;
  price: number;
  category: string;
  sport: string;
  color: string;
  tag?: string;
  isCustomizable: boolean;
  description: string;
  sizes: string[];
  href: string;
  image: string;
};

export const PRODUCTS: Product[] = [
  // ── Soccer ──────────────────────────────────────────
  {
    id: "aero-match-jersey",
    name: "Aero Match Jersey",
    price: 54,
    category: "Jerseys",
    sport: "Soccer",
    color: "#3dd9ff",
    tag: "Pro Team Issue",
    isCustomizable: true,
    description:
      "Regulation-cut match jersey in layered cooling mesh. Engineered for ninety minutes of sprint, press, and recovery.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/aero-match-jersey",
    image: "/images/products/soccer-1.webp",
  },
  {
    id: "striker-pro-jersey",
    name: "Striker Pro Jersey",
    price: 52,
    category: "Jerseys",
    sport: "Soccer",
    color: "#3dd9ff",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Lightweight jersey with sublimation-printed graphics and ventilation zones across the back panel.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/striker-pro-jersey",
    image: "/images/products/soccer-2.webp",
  },
  {
    id: "pitch-commander-kit",
    name: "Pitch Commander Kit",
    price: 58,
    category: "Jerseys",
    sport: "Soccer",
    color: "#3dd9ff",
    isCustomizable: true,
    description:
      "Full match kit with reinforced seams and moisture-wicking micro-mesh body. Built for high-press systems.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/pitch-commander-kit",
    image: "/images/products/soccer-3.webp",
  },
  {
    id: "full-kit-soccer",
    name: "Full Match Day Kit",
    price: 110,
    category: "Full Kits",
    sport: "Soccer",
    color: "#3dd9ff",
    tag: "Premium",
    isCustomizable: true,
    description:
      "Complete match day ensemble — jersey, shorts, and socks. Coordinated colorways with sublimation-printed crests.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/full-kit-soccer",
    image: "/images/products/soccer-full-1.webp",
  },
  {
    id: "soccer-training-top",
    name: "Training Top",
    price: 42,
    category: "Training Wear",
    sport: "Soccer",
    color: "#3dd9ff",
    isCustomizable: true,
    description:
      "Half-zip training layer with raglan sleeves and reflective piping. Ideal for pre-match warmups.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/soccer-training-top",
    image: "/images/products/soccer-4.webp",
  },
  {
    id: "soccer-away-jersey",
    name: "Away Kit Jersey",
    price: 54,
    category: "Jerseys",
    sport: "Soccer",
    color: "#3dd9ff",
    isCustomizable: true,
    description:
      "Contrast-color away jersey with tonal pattern and mesh underarm panels for breathability.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/soccer-away-jersey",
    image: "/images/products/soccer-5.webp",
  },
  {
    id: "soccer-goalkeeper-jersey",
    name: "Goalkeeper Jersey",
    price: 56,
    category: "Jerseys",
    sport: "Soccer",
    color: "#3dd9ff",
    isCustomizable: true,
    description:
      "Padded-elbow goalkeeper jersey in abrasion-resistant fabric. High-visibility colorways available.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/soccer-goalkeeper-jersey",
    image: "/images/products/soccer-6.webp",
  },
  {
    id: "soccer-custom-kit",
    name: "Custom Team Kit",
    price: 65,
    category: "Full Kits",
    sport: "Soccer",
    color: "#3dd9ff",
    tag: "New",
    isCustomizable: true,
    description:
      "Fully customizable kit with your team colors, crest, names, and numbers. Sublimation-printed for permanence.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/soccer-custom-kit",
    image: "/images/products/soccer-7.webp",
  },

  // ── Basketball ──────────────────────────────────────
  {
    id: "courtside-jersey",
    name: "Courtside Jersey",
    price: 48,
    category: "Jerseys",
    sport: "Basketball",
    color: "#ff9b3d",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Sleeveless jersey in 4-way stretch mesh with reinforced armholes. Built for the full-court press.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/courtside-jersey",
    image: "/images/products/basketball-1.webp",
  },
  {
    id: "hoop-dominator-short",
    name: "Hoop Dominator Short",
    price: 38,
    category: "Shorts",
    sport: "Basketball",
    color: "#ff9b3d",
    isCustomizable: true,
    description:
      "11-inch inseam basketball short with side vents and an internal drawcord. Motion-ready fabric.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/hoop-dominator-short",
    image: "/images/products/basketball-2.webp",
  },
  {
    id: "full-court-kit",
    name: "Full Court Kit",
    price: 82,
    category: "Full Kits",
    sport: "Basketball",
    color: "#ff9b3d",
    tag: "Premium",
    isCustomizable: true,
    description:
      "Complete uniform — jersey and shorts in matching colorway. Sublimation-printed team graphics.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/full-court-kit",
    image: "/images/products/basketball-3.webp",
  },
  {
    id: "basketball-shooting-shirt",
    name: "Shooting Shirt",
    price: 44,
    category: "Training Wear",
    sport: "Basketball",
    color: "#ff9b3d",
    isCustomizable: true,
    description:
      "Long-sleeve shooting shirt with quarter-zip and moisture-wicking knit. Pre-game essential.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/basketball-shooting-shirt",
    image: "/images/products/basketball-4.webp",
  },
  {
    id: "basketball-warmup",
    name: "Warmup Tracksuit",
    price: 95,
    category: "Track Suits",
    sport: "Basketball",
    color: "#ff9b3d",
    isCustomizable: true,
    description:
      "Full warmup suit with tapered pants and zip-up jacket. Lightweight ripstop with team customization.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/basketball-warmup",
    image: "/images/products/basketball-5.webp",
  },

  // ── Baseball ────────────────────────────────────────
  {
    id: "diamond-classic-jersey",
    name: "Diamond Classic Jersey",
    price: 52,
    category: "Jerseys",
    sport: "Baseball",
    color: "#ff4d2e",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Button-down jersey in moisture-wicking pinstripe fabric. Full button front with reinforced placket.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/diamond-classic-jersey",
    image: "/images/products/baseball-1.webp",
  },
  {
    id: "baseball-pullover",
    name: "Game Day Pullover",
    price: 46,
    category: "Jerseys",
    sport: "Baseball",
    color: "#ff4d2e",
    isCustomizable: true,
    description:
      "Full-zip pullover with raglan sleeves and contrast piping. Perfect for the dugout and beyond.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/baseball-pullover",
    image: "/images/products/baseball-2.webp",
  },
  {
    id: "baseball-full-uniform",
    name: "Full Game Uniform",
    price: 120,
    category: "Full Kits",
    sport: "Baseball",
    color: "#ff4d2e",
    tag: "Premium",
    isCustomizable: true,
    description:
      "Complete uniform — jersey, pants, and cap. Pinstripe or solid colorways with custom embroidery.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/baseball-full-uniform",
    image: "/images/products/baseball-3.webp",
  },
  {
    id: "baseball-training-tee",
    name: "Practice Tee",
    price: 34,
    category: "Training Wear",
    sport: "Baseball",
    color: "#ff4d2e",
    isCustomizable: true,
    description:
      "Relaxed-fit cotton-blend tee with moisture management. Batting cage to bullpen ready.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/baseball-training-tee",
    image: "/images/products/baseball-4.webp",
  },

  // ── Cricket ─────────────────────────────────────────
  {
    id: "command-cricket-uniform",
    name: "Command Cricket Uniform",
    price: 68,
    category: "Cricket Uniforms",
    sport: "Cricket",
    color: "#c6ff3d",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Full-sleeve performance kit with UPF-50 fabric and underarm cooling panels for long spells in the field.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/command-cricket-uniform",
    image: "/images/products/cricket-1.webp",
  },
  {
    id: "cricket-test-whites",
    name: "Test Match Whites",
    price: 72,
    category: "Cricket Uniforms",
    sport: "Cricket",
    color: "#c6ff3d",
    tag: "Pro",
    isCustomizable: true,
    description:
      "Traditional whites in modern performance fabric. Breathable mesh panels and reinforced stitching.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/cricket-test-whites",
    image: "/images/products/cricket-2.webp",
  },
  {
    id: "cricket-training-top",
    name: "Cricket Training Top",
    price: 48,
    category: "Training Wear",
    sport: "Cricket",
    color: "#c6ff3d",
    isCustomizable: true,
    description:
      "Long-sleeve training top with thumbholes and UPF-50 sun protection. Built for net sessions.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/cricket-training-top",
    image: "/images/products/cricket-3.webp",
  },
  {
    id: "cricket-color-kit",
    name: "Limited-Overs Color Kit",
    price: 65,
    category: "Cricket Uniforms",
    sport: "Cricket",
    color: "#c6ff3d",
    isCustomizable: true,
    description:
      "Vibrant limited-overs kit in bold colorways. Quick-dry sublimation print with team crest placement.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/cricket-color-kit",
    image: "/images/products/cricket-alt-1.webp",
  },
  {
    id: "cricket-keeper-gloves",
    name: "Keeper's Training Kit",
    price: 55,
    category: "Cricket Uniforms",
    sport: "Cricket",
    color: "#c6ff3d",
    isCustomizable: true,
    description:
      "Specialized keeper's kit with padded panels and flexible gussets. Designed for behind-the-stumps duty.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/cricket-keeper-gloves",
    image: "/images/products/cricket-alt-2.webp",
  },

  // ── Ice Hockey ──────────────────────────────────────
  {
    id: "tundra-training-top",
    name: "Tundra Training Top",
    price: 62,
    category: "Training Wear",
    sport: "Ice Hockey",
    color: "#7a8cff",
    isCustomizable: true,
    description:
      "Thermal-liner training shell with abrasion panels across the shoulders. Built for glass-to-glass minutes.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/tundra-training-top",
    image: "/images/products/ice-hockey-1.webp",
  },
  {
    id: "ice-hockey-jersey",
    name: "Rink Warrior Jersey",
    price: 78,
    category: "Jerseys",
    sport: "Ice Hockey",
    color: "#7a8cff",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Heavy-duty hockey jersey in 400gsm polyester with reinforced shoulders and fight strap.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/ice-hockey-jersey",
    image: "/images/products/ice-hockey-2.webp",
  },
  {
    id: "ice-hockey-full-kit",
    name: "Full Hockey Kit",
    price: 145,
    category: "Full Kits",
    sport: "Ice Hockey",
    color: "#7a8cff",
    tag: "Premium",
    isCustomizable: true,
    description:
      "Complete hockey uniform — jersey, pants, and socks. Sublimation-printed with your team identity.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/ice-hockey-full-kit",
    image: "/images/products/ice-hockey-3.webp",
  },
  {
    id: "hockey-warmup-jacket",
    name: "Warmup Jacket",
    price: 85,
    category: "Track Suits",
    sport: "Ice Hockey",
    color: "#7a8cff",
    isCustomizable: true,
    description:
      "Full-zip warmup jacket with fleece lining and team crest embroidery. Pre-game standard.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/hockey-warmup-jacket",
    image: "/images/products/ice-hockey-alt-1.webp",
  },
  {
    id: "hockey-away-jersey",
    name: "Away Jersey",
    price: 78,
    category: "Jerseys",
    sport: "Ice Hockey",
    color: "#7a8cff",
    isCustomizable: true,
    description:
      "Contrast-color away jersey with sublimation-printed graphics and reinforced elbow panels.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/hockey-away-jersey",
    image: "/images/products/ice-hockey-alt-2.webp",
  },

  // ── Track Suits ─────────────────────────────────────
  {
    id: "velocity-track-suit",
    name: "Velocity Track Suit",
    price: 112,
    category: "Track Suits",
    sport: "Track & Field",
    color: "#ff9b3d",
    tag: "New",
    isCustomizable: false,
    description:
      "Two-piece warm-up in a technical French terry. Quiet on the outside, engineered underneath.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/velocity-track-suit",
    image: "/images/products/track-suit-1.webp",
  },
  {
    id: "sprint-warmup-suit",
    name: "Sprint Warmup Suit",
    price: 98,
    category: "Track Suits",
    sport: "Track & Field",
    color: "#ff9b3d",
    isCustomizable: true,
    description:
      "Lightweight warmup suit with zip-off legs and reflective accents. Competition-day essential.",
    sizes: ["S", "M", "L", "XL"],
    href: "/products/sprint-warmup-suit",
    image: "/images/products/track-suit-2.webp",
  },
  {
    id: "recovery-track-pant",
    name: "Recovery Track Pant",
    price: 58,
    category: "Track Suits",
    sport: "Track & Field",
    color: "#ff9b3d",
    isCustomizable: true,
    description:
      "Tapered recovery pant with zip pockets and compression-fit cuffs. Post-race comfort.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/recovery-track-pant",
    image: "/images/products/track-suit-3.webp",
  },

  // ── Hoodies ─────────────────────────────────────────
  {
    id: "apex-tech-hoodie",
    name: "Apex Tech Hoodie",
    price: 74,
    category: "Hoodies",
    sport: "Training",
    color: "#ffffff",
    isCustomizable: true,
    description:
      "Brushed-back fleece with a tonal embroidered crest. Street-ready, team-field durable.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/apex-tech-hoodie",
    image: "/images/products/hoodies-1.webp",
  },
  {
    id: "urban-crew-hoodie",
    name: "Urban Crew Hoodie",
    price: 68,
    category: "Hoodies",
    sport: "Training",
    color: "#ffffff",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Classic pullover hoodie in 320gsm French terry. Kangaroo pocket with internal media port.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/urban-crew-hoodie",
    image: "/images/products/hoodies-2.webp",
  },
  {
    id: "performance-zip-hoodie",
    name: "Performance Zip Hoodie",
    price: 78,
    category: "Hoodies",
    sport: "Training",
    color: "#ffffff",
    isCustomizable: true,
    description:
      "Full-zip hoodie with articulated sleeves and moisture-wicking fleece. Gym-to-street versatility.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/performance-zip-hoodie",
    image: "/images/products/hoodies-3.webp",
  },
  {
    id: "team-pullover-hoodie",
    name: "Team Pullover Hoodie",
    price: 65,
    category: "Hoodies",
    sport: "Training",
    color: "#ffffff",
    isCustomizable: true,
    description:
      "Bulk-order team hoodie in heavy 350gsm cotton-poly. Custom crest and number printing available.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/team-pullover-hoodie",
    image: "/images/products/hoodies-4.webp",
  },
  {
    id: "color-block-hoodie",
    name: "Color Block Hoodie",
    price: 72,
    category: "Hoodies",
    sport: "Training",
    color: "#ffffff",
    tag: "New",
    isCustomizable: true,
    description:
      "Two-tone color block design with raglan sleeves and tonal drawcords. Stand out from the bench.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/color-block-hoodie",
    image: "/images/products/hoodies-5.webp",
  },

  // ── Duffel Bags ─────────────────────────────────────
  {
    id: "payload-duffel",
    name: "Payload Duffel",
    price: 89,
    category: "Duffel Bags",
    sport: "All Sports",
    color: "#ff4d2e",
    tag: "Field Kit",
    isCustomizable: false,
    description:
      "Water-resistant 40L duffel with a ventilated equipment bay and padded 16\" laptop sleeve.",
    sizes: ["One Size"],
    href: "/products/payload-duffel",
    image: "/images/products/duffel-1.webp",
  },
  {
    id: "game-day-duffel",
    name: "Game Day Duffel",
    price: 75,
    category: "Duffel Bags",
    sport: "All Sports",
    color: "#ff4d2e",
    isCustomizable: false,
    description:
      "Mid-size 30L duffel with shoe compartment and water-resistant base. Match-day essential.",
    sizes: ["One Size"],
    href: "/products/game-day-duffel",
    image: "/images/products/duffel-2.webp",
  },
  {
    id: "travel-duffel-pro",
    name: "Travel Duffel Pro",
    price: 110,
    category: "Duffel Bags",
    sport: "All Sports",
    color: "#ff4d2e",
    tag: "Premium",
    isCustomizable: false,
    description:
      "60L expedition duffel with wheels, telescoping handle, and multiple access points. Tournament-ready.",
    sizes: ["One Size"],
    href: "/products/travel-duffel-pro",
    image: "/images/products/duffel-3.webp",
  },
  {
    id: "compact-gear-bag",
    name: "Compact Gear Bag",
    price: 45,
    category: "Duffel Bags",
    sport: "All Sports",
    color: "#ff4d2e",
    isCustomizable: false,
    description:
      "18L compact duffel for daily training. External bat/racket sleeve and ventilated pocket.",
    sizes: ["One Size"],
    href: "/products/compact-gear-bag",
    image: "/images/products/duffel-4.webp",
  },
  {
    id: "team-transport-bag",
    name: "Team Transport Bag",
    price: 135,
    category: "Duffel Bags",
    sport: "All Sports",
    color: "#ff4d2e",
    isCustomizable: true,
    description:
      "80L team equipment bag with internal dividers and ID window. Ship gear for the whole squad.",
    sizes: ["One Size"],
    href: "/products/team-transport-bag",
    image: "/images/products/duffel-alt-1.webp",
  },

  // ── Karate ──────────────────────────────────────────
  {
    id: "karate-master-gi",
    name: "Karate Master Gi",
    price: 85,
    category: "Uniforms",
    sport: "Karate",
    color: "#ff4d2e",
    tag: "Bestseller",
    isCustomizable: true,
    description:
      "Traditional 100% cotton karate gi with reinforced stitching. Kata and kumite approved.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/karate-master-gi",
    image: "/images/products/karate-1.webp",
  },
  {
    id: "karate-competition-gi",
    name: "Competition Gi",
    price: 95,
    category: "Uniforms",
    sport: "Karate",
    color: "#ff4d2e",
    tag: "Pro",
    isCustomizable: true,
    description:
      "Lightweight competition gi in premium cotton blend. WKF-approved cut with pre-shrunk finish.",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    href: "/products/karate-competition-gi",
    image: "/images/products/karate-2.webp",
  },
  {
    id: "karate-training-top",
    name: "Training Top",
    price: 45,
    category: "Training Wear",
    sport: "Karate",
    color: "#ff4d2e",
    isCustomizable: true,
    description:
      "Lightweight training top with mesh ventilation panels. Dojo-to-outdoor versatility.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/karate-training-top",
    image: "/images/products/karate-3.webp",
  },
  {
    id: "karate-youth-gi",
    name: "Youth Gi",
    price: 55,
    category: "Uniforms",
    sport: "Karate",
    color: "#ff4d2e",
    isCustomizable: true,
    description:
      "Scaled-down karate gi for junior practitioners. Durable cotton with adjustable waist.",
    sizes: ["XS", "S", "M", "L"],
    href: "/products/karate-youth-gi",
    image: "/images/products/karate-4.webp",
  },
  {
    id: "karate-black-gi",
    name: "Black Belt Gi",
    price: 110,
    category: "Uniforms",
    sport: "Karate",
    color: "#ff4d2e",
    tag: "Premium",
    isCustomizable: true,
    description:
      "Premium black gi in heavyweight 14oz cotton. The choice of senior instructors and black belts.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    href: "/products/karate-black-gi",
    image: "/images/products/karate-5.webp",
  },
];

export const PRODUCT_IMAGES: Record<string, string[]> = {
  soccer: [
    "/images/products/soccer-1.webp",
    "/images/products/soccer-2.webp",
    "/images/products/soccer-3.webp",
    "/images/products/soccer-4.webp",
    "/images/products/soccer-5.webp",
    "/images/products/soccer-6.webp",
    "/images/products/soccer-7.webp",
    "/images/products/soccer-8.webp",
  ],
  "soccer-full": [
    "/images/products/soccer-full-1.webp",
    "/images/products/soccer-full-2.webp",
    "/images/products/soccer-full-3.webp",
    "/images/products/soccer-full-4.webp",
    "/images/products/soccer-full-5.webp",
    "/images/products/soccer-full-6.webp",
  ],
  basketball: [
    "/images/products/basketball-1.webp",
    "/images/products/basketball-2.webp",
    "/images/products/basketball-3.webp",
    "/images/products/basketball-4.webp",
    "/images/products/basketball-5.webp",
    "/images/products/basketball-6.webp",
    "/images/products/basketball-7.webp",
    "/images/products/basketball-8.webp",
    "/images/products/basketball-9.webp",
    "/images/products/basketball-10.webp",
  ],
  baseball: [
    "/images/products/baseball-1.webp",
    "/images/products/baseball-2.webp",
    "/images/products/baseball-3.webp",
    "/images/products/baseball-4.webp",
    "/images/products/baseball-5.webp",
    "/images/products/baseball-6.webp",
    "/images/products/baseball-7.webp",
    "/images/products/baseball-8.webp",
  ],
  cricket: [
    "/images/products/cricket-1.webp",
    "/images/products/cricket-2.webp",
    "/images/products/cricket-3.webp",
    "/images/products/cricket-4.webp",
    "/images/products/cricket-5.webp",
  ],
  "cricket-alt": [
    "/images/products/cricket-alt-1.webp",
    "/images/products/cricket-alt-2.webp",
    "/images/products/cricket-alt-3.webp",
    "/images/products/cricket-alt-4.webp",
    "/images/products/cricket-alt-5.webp",
    "/images/products/cricket-alt-6.webp",
    "/images/products/cricket-alt-7.webp",
    "/images/products/cricket-alt-8.webp",
    "/images/products/cricket-alt-9.webp",
    "/images/products/cricket-alt-10.webp",
  ],
  duffel: [
    "/images/products/duffel-1.webp",
    "/images/products/duffel-2.webp",
    "/images/products/duffel-3.webp",
    "/images/products/duffel-4.webp",
    "/images/products/duffel-5.webp",
  ],
  "duffel-alt": [
    "/images/products/duffel-alt-1.webp",
    "/images/products/duffel-alt-2.webp",
    "/images/products/duffel-alt-3.webp",
    "/images/products/duffel-alt-4.webp",
    "/images/products/duffel-alt-5.webp",
    "/images/products/duffel-alt-6.webp",
    "/images/products/duffel-alt-7.webp",
    "/images/products/duffel-alt-8.webp",
    "/images/products/duffel-alt-9.webp",
    "/images/products/duffel-alt-10.webp",
  ],
  hoodies: [
    "/images/products/hoodies-1.webp",
    "/images/products/hoodies-2.webp",
    "/images/products/hoodies-3.webp",
    "/images/products/hoodies-4.webp",
    "/images/products/hoodies-5.webp",
    "/images/products/hoodies-6.webp",
    "/images/products/hoodies-7.webp",
    "/images/products/hoodies-8.webp",
    "/images/products/hoodies-9.webp",
    "/images/products/hoodies-10.webp",
    "/images/products/hoodies-11.webp",
    "/images/products/hoodies-12.webp",
    "/images/products/hoodies-13.webp",
    "/images/products/hoodies-14.webp",
  ],
  "hoodies-alt": [
    "/images/products/hoodies-alt-1.webp",
    "/images/products/hoodies-alt-2.webp",
    "/images/products/hoodies-alt-3.webp",
    "/images/products/hoodies-alt-4.webp",
    "/images/products/hoodies-alt-5.webp",
    "/images/products/hoodies-alt-6.webp",
    "/images/products/hoodies-alt-7.webp",
    "/images/products/hoodies-alt-8.webp",
    "/images/products/hoodies-alt-9.webp",
    "/images/products/hoodies-alt-10.webp",
    "/images/products/hoodies-alt-11.webp",
    "/images/products/hoodies-alt-12.webp",
    "/images/products/hoodies-alt-13.webp",
    "/images/products/hoodies-alt-14.webp",
  ],
  "ice-hockey": [
    "/images/products/ice-hockey-1.webp",
    "/images/products/ice-hockey-2.webp",
    "/images/products/ice-hockey-3.webp",
    "/images/products/ice-hockey-4.webp",
    "/images/products/ice-hockey-5.webp",
    "/images/products/ice-hockey-6.webp",
    "/images/products/ice-hockey-7.webp",
    "/images/products/ice-hockey-8.webp",
    "/images/products/ice-hockey-9.webp",
    "/images/products/ice-hockey-10.webp",
  ],
  "ice-hockey-alt": [
    "/images/products/ice-hockey-alt-1.webp",
    "/images/products/ice-hockey-alt-2.webp",
    "/images/products/ice-hockey-alt-3.webp",
    "/images/products/ice-hockey-alt-4.webp",
    "/images/products/ice-hockey-alt-5.webp",
  ],
  karate: [
    "/images/products/karate-1.webp",
    "/images/products/karate-2.webp",
    "/images/products/karate-3.webp",
    "/images/products/karate-4.webp",
    "/images/products/karate-5.webp",
    "/images/products/karate-6.webp",
    "/images/products/karate-7.webp",
    "/images/products/karate-8.webp",
    "/images/products/karate-9.webp",
    "/images/products/karate-10.webp",
    "/images/products/karate-11.webp",
    "/images/products/karate-12.webp",
  ],
  "track-suit": [
    "/images/products/track-suit-1.webp",
    "/images/products/track-suit-2.webp",
    "/images/products/track-suit-3.webp",
  ],
};

export type CustomColor = {
  name: string;
  hex: string;
};

export const CUSTOM_COLORS: CustomColor[] = [
  { name: "Signal Red", hex: "#E30613" },
  { name: "Highlight Red", hex: "#FF5A63" },
  { name: "Deep Red", hex: "#B8000A" },
  { name: "Team Black", hex: "#0A0A0B" },
  { name: "Charcoal", hex: "#24242A" },
];

export const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Pick your sport",
    body: "Choose the discipline and kit type. Every Ulti product starts with the movement it has to survive.",
  },
  {
    step: "02",
    title: "Design your kit",
    body: "Swap colors, place your crest, add names and numbers. Your design updates live in 3D as you build.",
  },
  {
    step: "03",
    title: "Lock it in",
    body: "Get a detailed spec sheet, size run, and a fixed quote. No surprises, no hidden minimums on large orders.",
  },
  {
    step: "04",
    title: "Ship to the squad",
    body: "In-house production and QC before every delivery. Your kit arrives ready for the first whistle.",
  },
];

export const WHY_STATS = [
  { value: 500, suffix: "+", label: "Teams outfitted" },
  { value: 48, suffix: "h", label: "Design turnaround" },
  { value: 99, suffix: "%", label: "Delivery on time" },
  { value: 40, suffix: "+", label: "Countries shipped" },
];

export const NAV_LINKS = [
  { label: "Shop", href: "/shop" },
  { label: "Sports", href: "/sports" },
  { label: "Custom Uniforms", href: "/custom-uniforms" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
